#!/bin/sh

# This tool is developed by Sebastiano Stipa, Politecnico di Milano, 2020 

# USER INPUTS -----------------------------------------------------------
processors=6   # number of PC processors for parallel computation
#------------------------------------------------------------------------

echo "Starting OpenFOAM job at: " $(date)

cp -r 0.orig 0


blockMesh                                    | tee log.blockMesh



echo "Running decomposePar" 
decomposePar -force                                

echo "Running the decomposed case using the pimpleFoam solver" 
mpirun -np 4 pimpleFoam -parallel  | tee log.pimpleFoam
                             
reconstructPar

